spring:
  output:
    ansi:
      enabled: never
  datasource:
    url: jdbc:mysql://localhost/tutorial_scheduler?useSSL=false
    username: tutorial
    password: tutorial
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate-dilaect: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate:
      ddl-auto: validate